type Psychic {
    id: Int
    username: String!
    email: String!
    nicename: String!
    thumbnail: String
    specialties: [String!]
    tools: [String!]
    reading_style: String
}

extend type Query {
    psychic(id: Int): Psychic
    psychics(limit: Int): [Psychic]
}
