type Client implements Account{

}

extend type Query {
    client(id: Int): Client
    clients: [Client]
}

extend type Mutation {
    clientCreate(
        firstname: String!
        lastname: String!
        email: String!
        username: String!
        password: String!
        role: String!
        gender: String!
        dob: String!
        phone: String!
        timezone: String
        cardName: String!
        creditCard: String!
        expiration: String!
        securityCode: Int!
        address: String!
        city: String!
        state: String!
        zip: String!
        country: String!
    ): Client
    clientDelete(id: Int): Boolean
    clientUpdate(
        id: Int!
        firstname: String
        lastname: String
        email: String
        username: String
        password: String
        role: String
        gender: String
        dob: String
        phone: String
        timezone: String
        cardName: String
        creditCard: String
        expiration: String
        securityCode: Int
        address: String
        city: String
        state: String
        zip: String
        country: String
    ): Client
}